define({
    "movelayerup": "Move layer up",
    "movelayerdown": "Move layer down",
    "removelayer": "Remove Layer",
    "enabledisablelayer": "Enable/Disable layer",
    "showhidelegend": "Show/Hide legend",
    "getfeatureinfo": "Inspect layer",
    "layeropacity": "Modify layer opacity",
    "switchtopoint": "Switch to Point layer",
    "switchtoshaded": "Switch to Shaded layer",
    "confirmremovelayer": "Are you sure you want to remove the layer?",
    "dragdroplayer": "Drag and Drop the layer<br>to sort the layer's list",
    "baselayer": "Control BaseLayers",
    "overlay": "Control Overlays",
    "wmsLoader": "Control External WMS Servers",
    "fullscreen": "Fullscreen",
    "layersubicons": "Click to open the layer's menu",
    "selectaWMSServer": "Select a WMS Server",
    "addaWMSServer": "Add a WMS Server",
    "nolegendavailable": "The legend is not available",
    
    map_select_overlay: "Select Overlayer",
    map_baselayers: "Base Layers",
    map_selected_layers: "Selected Layers",
    map_show_bounds: "Show Map Boundaries",
    map_show_labels: "Show Map Labels"
});